"""
SHADE Agent Chat API
Routes LLM conversation through Google Gemini with real-time FortyGuard context.
No demo mode shortcuts. All responses are generated by live AI reasoning.
"""
from fastapi import APIRouter
from typing import Optional
import logging
from backend.schemas.agent import ChatRequest, AgentResponse, AgentMessage
from backend.agent.graph import shade_agent
from backend.agent.nim_client import invoke_nim_chat
from backend.agent.prompts import SHADE_SYSTEM_PROMPT
from backend.data.synthetic_grid import SyntheticGridGenerator
from backend.analytics.heri import calculate_heri

router = APIRouter(prefix="/api/agent", tags=["agent"])
logger = logging.getLogger(__name__)


def _build_live_context(district: str = "Maryvale") -> str:
    """Build real-time context from live grid data for the AI to reference."""
    try:
        cells = SyntheticGridGenerator.get_district_grid(district, hour=15.0)
        if not cells:
            return ""

        temps = [c.get("temp_2m", 42.0) for c in cells]
        svis = [c.get("svi", 0.50) for c in cells]
        canopies = [c.get("canopy_cover", 0.10) for c in cells]
        elderly = [c.get("elderly_density", 50) for c in cells]

        avg_temp = sum(temps) / len(temps)
        max_temp = max(temps)
        avg_svi = sum(svis) / len(svis)
        avg_canopy = sum(canopies) / len(canopies)
        total_elderly = sum(elderly)
        critical_cells = sum(1 for t in temps if t > 43.0)

        return (
            f"\n[LIVE DATA CONTEXT — {district}]\n"
            f"Grid: {len(cells)} cells (20m² resolution)\n"
            f"Avg 2m Air Temp: {avg_temp:.1f}°C | Max: {max_temp:.1f}°C\n"
            f"Critical cells (>43°C): {critical_cells}/{len(cells)}\n"
            f"Avg CDC SVI: {avg_svi:.2f} | Avg Canopy: {avg_canopy*100:.1f}%\n"
            f"Total elderly residents in grid: {int(total_elderly)}\n"
        )
    except Exception as e:
        logger.warning(f"Could not build live context: {e}")
        return ""


@router.post("/chat", response_model=AgentResponse)
def agent_chat(request: ChatRequest):
    """
    Runs the SHADE Agent with live Gemini AI reasoning.
    All responses are generated in real-time by the LLM with live grid data context.
    """
    # Extract the user's message from the flexible request schema
    latest_message = ""
    messages_payload = []

    if request.messages and len(request.messages) > 0:
        messages_payload = [{"role": msg.role, "content": msg.content} for msg in request.messages]
        latest_message = request.messages[-1].content
    elif request.message:
        latest_message = request.message
        messages_payload = [{"role": "user", "content": request.message}]
    elif request.content:
        latest_message = request.content
        messages_payload = [{"role": "user", "content": request.content}]
    elif request.query:
        latest_message = request.query
        messages_payload = [{"role": "user", "content": request.query}]

    if not latest_message:
        return AgentResponse(
            response="Please provide a question about heat vulnerability, cooling interventions, or district analysis.",
            artifacts={}
        )

    # Determine target district from message context
    district = "Maryvale"
    if "arcadia" in latest_message.lower():
        district = "Arcadia"

    # Build live data context for the AI
    live_context = _build_live_context(district)
    enriched_system_prompt = SHADE_SYSTEM_PROMPT + live_context

    # 1. Primary: Live Gemini AI Reasoning
    try:
        response_text = invoke_nim_chat(
            messages=messages_payload,
            system_prompt=enriched_system_prompt,
            fallback_response=None
        )

        if response_text and len(response_text.strip()) > 10:
            # Compute real artifacts from grid data
            cells = SyntheticGridGenerator.get_district_grid(district, hour=15.0)
            heri_cells = calculate_heri(cells) if cells else []
            critical_count = sum(1 for c in (heri_cells or cells or []) if c.get("heri_score", 0) > 80 or c.get("temp_2m", 0) > 43)

            return AgentResponse(
                response=response_text,
                artifacts={
                    "district": district,
                    "cells_analyzed": len(cells) if cells else 0,
                    "critical_cells": critical_count,
                    "status": "LIVE_AI_PROCESSED"
                }
            )
    except Exception as e:
        logger.error(f"Gemini AI call failed: {e}")

    # 2. Fallback: Decision pipeline agent
    try:
        result = shade_agent.run(
            messages=messages_payload,
            district=district,
            budget=50000.0,
            target="elderly"
        )

        return AgentResponse(
            response=result.get("response", "Analysis completed."),
            artifacts={
                "district": district,
                "budget_spent": result.get("allocation", {}).get("budget_spent", 0),
                "residents_covered": result.get("allocation", {}).get("residents_covered", 0),
                "avg_cooling_c": result.get("allocation", {}).get("avg_projected_cooling_c", 0),
                "status": "PIPELINE_PROCESSED"
            }
        )
    except Exception as e:
        logger.error(f"Agent pipeline also failed: {e}")
        return AgentResponse(
            response=f"I encountered an error processing your request for {district}. The backend services may be temporarily unavailable. Error: {str(e)}",
            artifacts={"status": "ERROR", "error": str(e)}
        )
